### ISSUE TITLE
XMLTools4YAWL doesn't handle all possible schema constructs

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#129]
```
The attached file cannot be uploaded:

"Could not successfully start case - problem initialising dynamic form 
from specification. Please see the log files for details."

Maybe this is a problem that has been solved in the mean time?


```

Original issue reported on code.google.com by `arthurte...@gmail.com` on 28 Aug 2008 at 4:59

**Comment by yawlfoundation** [comment]
```
BTW, the example XML data type was taken from:

http://www.datypic.com/books/defxmlschema/chapter11.html
```

Original comment by `arthurte...@gmail.com` on 28 Aug 2008 at 5:00

**Comment by yawlfoundation** [comment]
```
And now with attachment ...
```

Original comment by `arthurte...@gmail.com` on 28 Aug 2008 at 5:19

Attachments:
* [new82.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-129/comment-2/new82.ywl)

**Comment by yawlfoundation** [comment]
```
Removing the choice type does not resolve the problem (see attached 
specification).
```

Original comment by `arthurte...@gmail.com` on 28 Aug 2008 at 5:45

Attachments:
* [new83.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-129/comment-3/new83.ywl)

**Comment by yawlfoundation** [comment]
```
The more complex schema constructs are not sufficiently broken down into their 
simple
type bases required by the engine for form generation (see also issue 125). I'll
change the summary of this issue to reflect this issue. 
```

Original comment by `yawl.mic...@gmail.com` on 28 Aug 2008 at 12:03
* Changed title: **XMLTools4YAWL doesn't handle all possible schema constructs**
* Changed state: **Started**
* Added labels: **Category-Engine**, **Priority-Medium**, **Type-Enhancement**
* Removed labels: **Category-Editor**, **Priority-High**, **Type-Defect**

**Comment by adamsmj** [comment]
bug was fixed many years ago
