### ISSUE TITLE
Save file in yawleditor 3.0beta (build 407) causes exception

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#518]
```
What steps will reproduce the problem?
1. Run sh yawleditor.sh
2. Verify connection to server
3. Start any new net
4. Attempt to save or save as

What is the expected output? What do you see instead?

The document is not saved, all editor menu items become and remain disabled and 
the wait cursor never changes to a standard cursor. Editing functions continue 
to function normally.

I obtained the following diagnostic output.

Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at org.yawlfoundation.yawl.editor.ui.specification.SpecificationFileHandler.getSuggestedFileName(SpecificationFileHandler.java:154)
	at org.yawlfoundation.yawl.editor.ui.specification.SpecificationFileHandler.promptForSaveFileName(SpecificationFileHandler.java:164)
	at org.yawlfoundation.yawl.editor.ui.specification.SpecificationFileHandler.saveFileAs(SpecificationFileHandler.java:90)
	at org.yawlfoundation.yawl.editor.ui.specification.FileOperations.processAction(FileOperations.java:107)
	at org.yawlfoundation.yawl.editor.ui.specification.FileOperations.access$000(FileOperations.java:35)
	at org.yawlfoundation.yawl.editor.ui.specification.FileOperations$1.run(FileOperations.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

What version of the product are you using? On what operating system?

3.0beta build 407 on Ubuntu 14.04. Java version:
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

Please provide any additional information below.

It does not apparently matter whether I save as or save.
```

Original issue reported on code.google.com by `scott.de...@gmail.com` on 15 May 2014 at 6:24

**Comment by yawlfoundation** [comment]
```
Fixed in the latest build (452): 
http://yawlfoundation.org/latest/three/YAWLEditor3.0beta.zip

Thanks for reporting this problem. Can you please add a comment to verify the 
fix?
```

Original comment by `yawl.mic...@gmail.com` on 15 May 2014 at 10:49
* Changed state: **ClosePending**

**Comment by yawlfoundation** [comment]
```
Could you tell me where the editor keeps its configuration, so that I can
remove it and try with a fresh config? After I opened a known .yawl file
yesterday with the editor, the problem disappeared. I'll need to test it
with an empty config.
```

Original comment by `scott.de...@gmail.com` on 16 May 2014 at 2:23

**Comment by yawlfoundation** [comment]
```
I found and deleted the configuration and tried it again. It works fine.


On Fri, May 16, 2014 at 10:22 AM, Scott Deerwester <
scott.deerwester@gmail.com> wrote:
```

Original comment by `scott.de...@gmail.com` on 16 May 2014 at 2:31

**Comment by yawlfoundation** [comment]
```
Great, thanks for reporting back.
```

Original comment by `yawl.mic...@gmail.com` on 17 May 2014 at 12:30
* Changed state: **Fixed**

**Comment by ygu** [comment]
Could you indicate where and what configuration files you found and removed ?
I have the same issue here...

**Comment by adamsmj** [comment]
The cause of the original problem was not due to any configuration issues. If you are having trouble saving a file, please update your editor to the latest version (b.607) if you haven't already, and post your YAWLEditor.log file (in the editor directory) to this thread, thanks.

**Comment by ygu** [comment]
Yes, I can't save any file. Even after a fresh install. Just create a new net with only one task connected to the input and output conditions -> save. I got the "saving" info, in the bottom of the screen, and the progress indication quickly reaches the right end, but then it's stuck here, and nothing is saved. I can still use the editor, and try to save again. But nothing is saved.
I'm using the version installed by the YAWL-3.0.1-linux-x64-installer.run installer. Isn't it the last one ?
The YAWLEditor.log file is surprisingly empty.

**Comment by adamsmj** [comment]
On the editor's menu bar, go to "Help -> Check for Updates". Then 'download and restart'.

**Comment by ygu** [comment]
Ok, it worked, thanks. But I'm confused: can't we just download the last version from the website ?

**Comment by adamsmj** [comment]
Yes, the downloadable version on the website is the latest full release version, but (as with most software) updates/fixes are being done all the time. The YAWL editor & control panel give you the ability to update to the latest builds, i.e. those that occur between full releases, as soon as they are available.
