### ISSUE TITLE
Can not dowload layout 

### ISSUE THREAD

**Issue by vascoosx** [yawlfoundation/yawl#548]
I tried to load a layout but was met with the following message: 

> The specification loaded successfully, but the layout data is invalid. A basic default layout will be applied

I am using YAWL 4.1 on windows 7.

**Comment by yawlfoundation** [comment]
Not a bug: Any specification created via to version 2 will not include any layout information, while any created after that version may have its layout data corrupted in some way. In either case, the specification will still load, and its layout will be (re)generated - it may look messy on more complex models. The message you received is not an issue, merely an informational message about what has happened on load.
