### ISSUE TITLE
Data variables issues in MI tasks

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#549]
[MI_data.yawl.gz](https://github.com/yawlfoundation/yawl/files/283449/MI_data.yawl.gz)

To describe the issues ‘MI_data.yawl’ specification (attached) is used.

**#1**
**_Steps_**: open ‘Data variables’ window for MI task ‘B’ -> drag-and-drop net variables ‘hoppers’ and ‘test’ -> press ‘OK’ -> Save the specification
**_Result_**: error saving file (Note: there is no error if variable ‘hoppers’ is marked as MI) 
![image](https://cloud.githubusercontent.com/assets/14101966/15563329/f33ad7d6-234a-11e6-8ac1-a8be48880e5f.png)

**#2** 
**_Steps_**: open ‘Data variables’ window for MI task B -> create task variable by dragging-and-dropping net variable ‘hoppers’ -> save, close and reopen the specification -> open ‘Output bindings’ for task B
**_Result_**: Output binding for ‘hoppers’ variable is not defined

**#3**
**_Steps_**: select MI task variable whose output binding is not defined (e.g. ‘hoppers’ in #2) -> press ‘Mark as MI’
**_Result_**: the editor freezes.

**#4**
**_Steps_**: open ‘Data variables’ window for MI task B -> drag-and-drop net variable ‘hoppers’ -> press ‘OK’ -> open ‘Data variables’ window for MI task B -> perform one of the following:
1) drag-and-drop net variable ‘test’ -> press ‘OK’/’Apply’
2) open and close Input / Output / Quick view bindings  -> press ‘OK’/’Apply’
**_Result_**: the editor freezes.

 **#5**
**_Steps_**: open ‘Data variables’ window for MI task B -> drag-and-drop net variable ‘hoppers’ -> mark it as MI -> press ‘OK’ -> open ‘Data variables’ window for MI task B
**_Result_**: either 1) variable ‘hoppers’ is not marked as MI; OR 2) ‘invalid or empty input binding’ message depicted below. (When the variable with ‘input binding’ error is removed, ‘Apply’ and ‘OK’ buttons are not active.)
![image](https://cloud.githubusercontent.com/assets/14101966/15563359/52037aca-234b-11e6-8e9b-10dab172cb39.png)

**Comment by yawlfoundation** [comment]
All fixed:
1. DV dialog no longer allows saving for an MI task unless the task variable list is empty, or there is one variable set as the MI variable. A warning message has also been added to that effect.

2. Output bindings for MI tasks now retained correctly.

3. Fixed with 2.

4. Fixed with 1.

5. Fixed with 2.
