### ISSUE TITLE
Task gets disconnected

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#550]
[gateways.yawl.gz](https://github.com/yawlfoundation/yawl/files/285666/gateways.yawl.gz)

**Steps**: open specification ‘gateways.yawl’ (attached) -> create a task -> connect it with ‘Split’ and ‘Join’ tasks -> label the task ‘A’ -> save the specification -> create another task and connect it with ‘Split’ and ‘Join’ tasks -> save the specification

**Result**: error ‘Task:A is disconnected’:
![image](https://cloud.githubusercontent.com/assets/14101966/15595909/59e99e02-2406-11e6-948b-4b12d14617f9.png)

When the specification is closed and reopened:
![image](https://cloud.githubusercontent.com/assets/14101966/15595919/6977df96-2406-11e6-9f33-aa061b77c624.png)

The same issue occurs for all types of tasks and gateways. The issue only occurs when the first task is labelled – unlabelled tasks stay connected.

**Comment by yawlfoundation** [comment]
fixed (b.691) - implicit condition id was not being updated
