### ISSUE TITLE
Error when changing net variable data type

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#551]
[dataTypeChange.yawl.gz](https://github.com/yawlfoundation/yawl/files/285729/dataTypeChange.yawl.gz)

**Steps**: open ‘dataTypeChange.yawl’ specification (attached) -> open ‘Data Variables’ window for the net -> create net variable of type ‘integer’ and press ‘Apply’ (initial value ‘0’ will be automatically added) -> change Type to ‘date’ (initial value is removed) -> press ‘Apply’

**Result**: error ‘invalid data type for variable value’:

![image](https://cloud.githubusercontent.com/assets/14101966/15597568/b938af34-2414-11e6-99a7-b9a216ccf2ce.png)

**Comment by yawlfoundation** [comment]
Fixed.
