### ISSUE TITLE
Remove net variable – inactive Apply and OK buttons

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#552]
[removeNetVariable.yawl.gz](https://github.com/yawlfoundation/yawl/files/285743/removeNetVariable.yawl.gz)

**Steps**: open ‘removeNetVariable.yawl’ specification (attached) -> open ‘Data Variables’ window for the net -> remove variable ‘test’

**Result**: ‘Apply’ and ‘OK’ buttons are not enabled:

![image](https://cloud.githubusercontent.com/assets/14101966/15597820/733e55ee-2417-11e6-9d86-8d78471ea93d.png)

**Comment by yawlfoundation** [comment]
Fixed
