### ISSUE TITLE
Removing data definitions

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#553]
**Steps**: create/open any net -> open ‘Data Definitions’ -> select and remove all content (status bar displays ‘OK’ – image below) -> press ‘Done’

![image](https://cloud.githubusercontent.com/assets/14101966/15598115/6da92aac-241a-11e6-96f3-c6070f55fc7c.png)

**Result**: the editor freezes

**Comment by yawlfoundation** [comment]
Fixed
