### ISSUE TITLE
Saving specification: output binding not defined for a variable used in a split predicate

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#555]
[noOutBinding_save.yawl.gz](https://github.com/yawlfoundation/yawl/files/290424/noOutBinding_save.yawl.gz)

The Editor allows saving a specification in which output binding is not defined for a variable used in a split predicate without giving any warning, though routing will not work correctly at run-time (e.g., in the attached specification ‘noOutBinding_save.yawl’):  

![image](https://cloud.githubusercontent.com/assets/14101966/15664849/845e0d34-274a-11e6-96ac-d2ae962b7a54.png)

**Comment by yawlfoundation** [comment]
No change required.

Split predicates reference net variables. The net variable in this case (test) is defined with an initial (default) value of 0. If no tasks change that value via an output binding, then that is the value tested in the predicate. That is, it is not necessary for a task to have an output binding to that net variable for the predicate to be valid.
