### ISSUE TITLE
Removing and adding a task with the same label – resource settings issue

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#556]
**Steps**: create/open a specification -> add a new task with a label (e.g., “A”) -> define resource settings for the task (e.g., enable system offer/allocation/start) -> save the specification -> remove the task and create another task with the same label (“A”) -> select the task and open ‘Resourcing’ window (all resource settings previously defined are still there) -> save, close and reopen the specification -> open ‘Resourcing’ window for the task (“A”)

**Result**: resource settings for the task (“A”) are not defined

**Comment by yawlfoundation** [comment]
fixed (b.691) - cached resource settings were not completely removed with task deletion
