### ISSUE TITLE
Saving incorrect data binding – no warning

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#557]
[incorrectDataBindingNoWarning.yawl.gz](https://github.com/yawlfoundation/yawl/files/295103/incorrectDataBindingNoWarning.yawl.gz)

**Steps**: open the attached specification -> open ‘Data variables’ for task ‘A’ -> open output binding for the task variable ‘tvar’ -> modify the binding as on the picture below and save the specification:

![image](https://cloud.githubusercontent.com/assets/14101966/15737625/664fc7d2-28ea-11e6-95e7-2d08ac36dfb9.png)

**Result**: the specification is saved with ‘no problems reported’ (the binding is removed).

**Comment by yawlfoundation** [comment]
fixed in latest release
