### ISSUE TITLE
Definition of ‘separation of duties’ constraint

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#559]
[separationOfDuties.yawl.gz](https://github.com/yawlfoundation/yawl/files/299820/separationOfDuties.yawl.gz)

**#1**
When defining resources for a task (e.g., task ‘c’ in the attached specification ‘separationOfDuties.yawl’) and selecting constraint ‘do not choose completer(s) of task’, it is not possible to choose a parallel task (e.g., task ‘b’).

**#2**
**_Steps_**: select a task (e.g. task ‘a’ in the attached specification) and open ‘Resourcing’ window -> select ‘enable system offer/allocation/start’ for one user -> specify the same resource settings for another task (e.g., for task ‘d’) -> additionally, for task ‘d’ select constraint ‘do not choose completer(s) of task a’ -> save the specification

**_Result_**: ‘no problems reported’ (the constraint makes no sense when two tasks are assigned to the same user). (During execution task ‘d’ is not offered to any users.)

**Comment by yawlfoundation** [comment]
1. This is designed behaviour. 4 eyes applies to _completers_ of a previous task. Parallel tasks are not completed before reference task is enabled, so 4 eyes can't be applied to parallel tasks.

2. User warning is now displayed.
