### ISSUE TITLE
Definition of large font sizes for task labels

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#560]
[colours.yawl.gz](https://github.com/yawlfoundation/yawl/files/301745/colours.yawl.gz)

When font size for tasks in the attached specification (‘colours.yawl’) is modified, it looks as expected:

![image](https://cloud.githubusercontent.com/assets/14101966/15844502/296a61ca-2cae-11e6-9b32-1ac89c363d16.png)

When the specification is saved, closed and opened again, it looks like on the figure below:

![image](https://cloud.githubusercontent.com/assets/14101966/15844510/36f54490-2cae-11e6-94b5-6e94f4ca3a0f.png)

**Comment by yawlfoundation** [comment]
fixed.
