### ISSUE TITLE
Special symbols removed from WI name - no warning in the Editor

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#561]
[specialSymbols.yawl.gz](https://github.com/yawlfoundation/yawl/files/301760/specialSymbols.yawl.gz)

The Editor allows using special symbols in task labels (e.g., task A%B# in the attached specification ‘specialSymbols.yawl’), however, when decomposition is created for the task, special symbols are removed from the name without any warning to a user; during the execution the user sees the modified task name (e.g. ‘AB’ instead of ‘A%B#’):

![image](https://cloud.githubusercontent.com/assets/14101966/15844906/9721246c-2cb1-11e6-9324-ea29ace70a84.png)

![image](https://cloud.githubusercontent.com/assets/14101966/15844912/a067de26-2cb1-11e6-8bcb-ad5443069c79.png)

**Comment by yawlfoundation** [comment]
Element and decomposition ids must not contain invalid XML characters. When a label is used to create an id, the invalid chars are removed. A user warning is now displayed.
