### ISSUE TITLE
User duplication

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#562]
[YAWLOrgDataExport.ybkp.gz](https://github.com/yawlfoundation/yawl/files/304089/YAWLOrgDataExport.ybkp.gz)

[users.yawl.gz](https://github.com/yawlfoundation/yawl/files/304090/users.yawl.gz)

[Exception Handler.html.gz](https://github.com/yawlfoundation/yawl/files/304091/Exception.Handler.html.gz)

**Steps**: import the attached organisational model (it contains 2 positions (position2 reports to position1) and one user defined for each position (user1 and user2) -> open tab ‘Users’, select user2, then select user1 (without making any changes to the users) -> open tab ‘Org Data’, tab ‘Positions’ and select position2 (user2 is listed twice in ‘Members’ as on Figure 1) -> open tab ‘Cases’, load the attached specification (‘users.yawl’) and start a case -> log out and login as user1 (password: yawl) -> accept offer for task ‘a’ and press ‘Delegate’ (user2 is listed twice as on Figure 2) -> select the second entry for user2 and press ‘OK’.

**Result**: Exception Handler.html (attached)

Figure 1:
![image](https://cloud.githubusercontent.com/assets/14101966/15884406/82b36e3a-2d93-11e6-8711-efe5542e302c.png)

Figure 2:
![image](https://cloud.githubusercontent.com/assets/14101966/15884409/8c5a0f16-2d93-11e6-8354-e8ba0ee6e8fe.png)

(Similar behaviour is observed for roles)

**Comment by yawlfoundation** [comment]
fixed in resource service build 3977.
