### ISSUE TITLE
Worklet duplication

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#563]
**Steps**: Download a stored worklet into the Editor -> save the specification -> press ‘Store the current specification as a worklet’ -> close the specification -> press ‘Download a stored worklet into the Editor’

**Result**: The worklet appears twice in the list, e.g., on the figure below:

![image](https://cloud.githubusercontent.com/assets/14101966/15950266/910b9e18-2ef0-11e6-9429-37a1493439e7.png)

**Comment by yawlfoundation** [comment]
fixed for build 697. basically, saving a file to disk for the first time (as in this case) gives it a new spec ID, so on upload its actually 2 different specs (by id). Fixed so that the id is unchanged in this use case.
