### ISSUE TITLE
Removed worklets are in the list of uploaded worklets

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#564]
Removed unreferenced worklets are shown in the list of uploaded worklets:
(they disappear after restarting the Editor)

![image](https://cloud.githubusercontent.com/assets/14101966/15950487/b9fbe452-2ef2-11e6-8fd6-09336bbfe0d7.png)
![image](https://cloud.githubusercontent.com/assets/14101966/15950490/bdd540f0-2ef2-11e6-9d90-3d2f4dd6ca48.png)
![image](https://cloud.githubusercontent.com/assets/14101966/15950493/c2031f12-2ef2-11e6-8638-f8380726d541.png)
![image](https://cloud.githubusercontent.com/assets/14101966/15950494/c788ecdc-2ef2-11e6-9706-c37ccc894109.png)

**Comment by yawlfoundation** [comment]
Fixed: removed worklet was getting left in cache
