### ISSUE TITLE
Removing unreferenced worklets

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#565]
If a ruleset is removed using ‘Remove an existing rule set’ button, worklets that were referenced by this ruleset can be removed using ‘Remove worklets no longer referred to by any ruleset’ button. However, when all rules from a ruleset are removed individually via ‘Rule Browser’, the related worklets do not appear on the list of unreferenced worklets and they cannot be removed using ‘Remove worklets no longer referred to by any ruleset’ button, e.g.:

![image](https://cloud.githubusercontent.com/assets/14101966/15950892/8ea26ad4-2ef6-11e6-8d0f-d512ac52a412.png)
![image](https://cloud.githubusercontent.com/assets/14101966/15950898/93872238-2ef6-11e6-87a3-5aa9762960b2.png)
![image](https://cloud.githubusercontent.com/assets/14101966/15950904/a6ac1152-2ef6-11e6-9d6f-0762f47ae44b.png)

(testWorklet2 is not referenced by any ruleset)

**Comment by yawlfoundation** [comment]
fixed for build 696
