### ISSUE TITLE
Data variables order in a worklet task 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#566]
[main.yawl.gz](https://github.com/yawlfoundation/yawl/files/308217/main.yawl.gz)
[main.xrs.gz](https://github.com/yawlfoundation/yawl/files/308218/main.xrs.gz)
[bWorklet.yawl.gz](https://github.com/yawlfoundation/yawl/files/308219/bWorklet.yawl.gz)

Exception in the log when executing the attached specification (‘main.yawl’), as depicted in the figure below. It seems to be related to the order of data variables in task ‘b’ – if variable ‘v1’ is listed first, a case can be completed.

![image](https://cloud.githubusercontent.com/assets/14101966/15952838/dcce74b2-2f07-11e6-9cd8-4848799bfc3c.png)

**Comment by yawlfoundation** [comment]
fixed in latest worklet service build

**Comment by yawlfoundation** [comment]
fixed in latest worklet service build
