### ISSUE TITLE
Worklet execution issue – using a subset of the variables from the parent task

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#567]
[diffVarNum.xrs.gz](https://github.com/yawlfoundation/yawl/files/308518/diffVarNum.xrs.gz)
[diffVarNum.yawl.gz](https://github.com/yawlfoundation/yawl/files/308519/diffVarNum.yawl.gz)
[worklet.yawl.gz](https://github.com/yawlfoundation/yawl/files/308520/worklet.yawl.gz)

Exception in the log when executing the attached specification (‘diffVarNum.yawl’), as depicted on the figure below (a subset of the variables from the parent task is used).

![image](https://cloud.githubusercontent.com/assets/14101966/15956970/47216960-2f2f-11e6-9ed0-4f77008cda22.png)

**Comment by yawlfoundation** [comment]
This is a user (designer) error. A worklet cannot map back to a parent a variable it has no knowledge of. The onus is on the person designing the worklet that ALL of the output variables expected by the parent task are delivered by the worklet.
