### ISSUE TITLE
Process configuration - saving a specification

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#568]
[processConfiguration.yawl.gz](https://github.com/yawlfoundation/yawl/files/311056/processConfiguration.yawl.gz)

**Steps**: open the attached specification (‘processConfiguration.yawl’) -> press ‘Apply process configuration’ button (twice if nothing happens; error messages are displayed in the status bar as in Figure 1) -> Save, close and reopen the specification

Figure 1:
![image](https://cloud.githubusercontent.com/assets/14101966/15994855/cf7c01ec-3152-11e6-97ab-4bbd591cbfed.png)

**Result**:

![image](https://cloud.githubusercontent.com/assets/14101966/15994861/deeb21bc-3152-11e6-9a5a-c5e6f3e18566.png)

**Comment by yawlfoundation** [comment]
fixed in build 706
