### ISSUE TITLE
Exception when executing a specification with recursive worklet substitution

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#571]
[mainWorkletRecursive.yawl.gz](https://github.com/yawlfoundation/yawl/files/311264/mainWorkletRecursive.yawl.gz)
[mainWorkletRecursive.xrs.gz](https://github.com/yawlfoundation/yawl/files/311265/mainWorkletRecursive.xrs.gz)
[recursiveWorklet.yawl.gz](https://github.com/yawlfoundation/yawl/files/311266/recursiveWorklet.yawl.gz)
[recursiveWorklet.xrs.gz](https://github.com/yawlfoundation/yawl/files/311267/recursiveWorklet.xrs.gz)
[otherWorklet.yawl.gz](https://github.com/yawlfoundation/yawl/files/311268/otherWorklet.yawl.gz)
[exception.docx.gz](https://github.com/yawlfoundation/yawl/files/311269/exception.docx.gz)

When executing the attached specification (‘mainWorkletRecursive.yawl’), a case is completed with an exception in the log (attached file ‘exception.docx’).

**Comment by yawlfoundation** [comment]
fixed in latest worklet service build
