### ISSUE TITLE
Changing custom service 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#572]
[decomposition.yawl.gz](https://github.com/yawlfoundation/yawl/files/312956/decomposition.yawl.gz)

**Steps**: open the attached specification (‘decomposition.yawl’) -> change Custom Service for tasks ‘a’, ‘b’ and ‘c’ to ‘Default Worklist’ -> save the specification (optionally close and reopen it)

**Result**: Custom Service for tasks ‘a’, ‘b’ and ‘c’ is not modified

**Comment by yawlfoundation** [comment]
fixed for build 685
