### ISSUE TITLE
Repetition of the ‘Invalid task selection’ warning

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#573]
[resourceConstraint.yawl.gz](https://github.com/yawlfoundation/yawl/files/313026/resourceConstraint.yawl.gz)

**Steps**: Open the attached specification (‘resourceConstraint.yawl’) -> select task ‘b’ and open the ‘Resourcing’ window for the task (warning window is displayed as in Figure 1, close it) -> press ‘OK’ (without making any changes to resources) -> open again the ‘Resourcing’ window for task ‘b’ (the warning is displayed again) -> repeat the steps for task ‘c’ (warning window is displayed as in Figure 2).

**Result**: window ‘Invalid Task Selection’ is displayed every time ‘Resourcing’ window for task ‘b’ or task ‘c’ is opened (the warning is correct, as task ‘a’ was removed from the specification). After saving, closing and reopening the specification the warning window is still displayed, it disappears only after resources for tasks ‘b’ and ‘c’ are modified. 

**Figure 1**
![image](https://cloud.githubusercontent.com/assets/14101966/16029167/f47e9644-3229-11e6-8d37-79528d8b6d01.png)

**Figure 2**
![image](https://cloud.githubusercontent.com/assets/14101966/16029174/02918e4e-322a-11e6-8cbd-e554568dc6c0.png)

**Comment by yawlfoundation** [comment]
fixed for build 685
