### ISSUE TITLE
‘Actions’ area in the Rule Browser

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#574]
If the size of Windows screen items is increased (more than 100%), then ‘Actions’ area in the Rule Browser is not fully visible (125%) or not visible (150%).

**Figure 1**: Windows screen settings
![image](https://cloud.githubusercontent.com/assets/14101966/16031452/b0932f70-323e-11e6-80cc-c043f8ec7213.png)

**Figure 2**: Rule Browser - 100% (actions are visible)
![image](https://cloud.githubusercontent.com/assets/14101966/16031454/bab81772-323e-11e6-84e1-8048ea04f5ac.png)

**Figure 3**: Rule Browser - 125% (list of actions is not visible)
![image](https://cloud.githubusercontent.com/assets/14101966/16031459/c48db6c6-323e-11e6-8967-a2c18f5a9993.png)

**Figure 4**: Rule Browser - 150% (‘Actions’ tab is not visible)
![image](https://cloud.githubusercontent.com/assets/14101966/16031462/cef58bfc-323e-11e6-924a-f504c62df427.png)

**Comment by yawlfoundation** [comment]
fixed for build 697, so that the Actions table can always be seen. Note that the dialog is resizable, so on larger magnifications will need to be resized out by the user.
