### ISSUE TITLE
User-defined data: issues with ‘sequence’ type

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#575]
[complexData.yawl.gz](https://github.com/yawlfoundation/yawl/files/315408/complexData.yawl.gz)

**#1**

**Steps**: load the attached specification in Engine (‘complexData.yawl’) and start task ‘a’ -> do not choose any element for ‘testItem’ (minOccurs=0) and press ‘Complete’ -> start task ‘b’ 

**Result**: user will see the screen below:
![image](https://cloud.githubusercontent.com/assets/14101966/16067730/7010ec34-3302-11e6-85a8-c501fbe58eaf.png)

**#2**

In the attached specification, the maximum number of elements in the ‘TestSequence’ type is defined as 3 (maxOccurs=3), however, it is not possible to add the second element, e.g., as shown in the Figure below:
![image](https://cloud.githubusercontent.com/assets/14101966/16067734/7c2672be-3302-11e6-9df3-05b6e1bfaa08.png)

**Comment by yawlfoundation** [comment]
1. Fixed: Input-only enumerated variable with minOccurs=0 will show an empty value instead of 'choose' if no value previously chosen.

2. Fixed
