### ISSUE TITLE
Variable number of instances in MI task

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#577]
[MIAtomic.yawl.gz](https://github.com/yawlfoundation/yawl/files/322703/MIAtomic.yawl.gz)

**#1**

**Steps**: open the attached specification (‘MIatomic.yawl’) and open M-I Attributes for task ‘b’ -> select option ‘Variable’ for ‘Maximum’ -> then select option ‘Variable’ for ‘Threshold’  

**Results**:

![image](https://cloud.githubusercontent.com/assets/14101966/16182991/8bf17f22-36ef-11e6-833d-c21572098381.png)
![image](https://cloud.githubusercontent.com/assets/14101966/16182994/92a31114-36ef-11e6-8ee4-5021a0754a6f.png)

**#2**

**Steps**: open the attached specification (‘MIatomic.yawl’) and open M-I Attributes for task ‘b’ -> select option ‘Variable’ for ‘Minimum’, ‘Maximum’ and ‘Threshold’ -> press ‘OK’ -> save the specification -> open M-I Attributes for task ‘b’

**Result**: all values are set to ‘Exactly’:
![image](https://cloud.githubusercontent.com/assets/14101966/16183004/ae742d56-36ef-11e6-8c22-832487aaff8b.png)

**Comment by yawlfoundation** [comment]
fixed in build 699
