### ISSUE TITLE
Issues related to decomposition-level default extended attributes

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#579]
[extendedAttributesDecomposition.yawl.gz](https://github.com/yawlfoundation/yawl/files/324834/extendedAttributesDecomposition.yawl.gz)
[extendedAttributesReadOnly.yawl.gz](https://github.com/yawlfoundation/yawl/files/324835/extendedAttributesReadOnly.yawl.gz)

**#1**

When executing an attached specification ‘extendedAttributesDecomposition.yawl’:
a) Drop-down list size is not aligned with the font size (in Firefox browser, OK in Google Chrome);
b) Font colour is not changed for the ‘amount’ field (in Google Chrome, OK in Firefox);
c) Page background colour is not changed (also page background image was not used when tested);
d) The title is not affected by font settings:

Firefox:
![image](https://cloud.githubusercontent.com/assets/14101966/16218634/06fde934-37c3-11e6-8ca1-f0f210593c38.png)

Google Chrome:
![image](https://cloud.githubusercontent.com/assets/14101966/16218638/124f935a-37c3-11e6-8f7a-22b203d4cf05.png)

**#2**

**Steps**: copy a path to an image to the clipboard  -> open attached specification ‘extendedAttributesDecomposition.yawl’ in the Editor -> open ‘Extended Attributes’ for task ‘abc’ -> select ‘Page Background Image’ attribute and place the cursor in the value field -> press CTRL+V (paste image path from the clipboard)

**Result**:  the Editor freezes (OK if the path is typed manually)

**#3**

**Steps**: open specification ‘extendedAttributesDecomposition.yawl’ -> open ‘Extended attributes’ for task ‘abc’ -> delete attributes ‘Font’ and ‘Heading Font’ -> save the specification -> reopen ‘Extended attributes’ for task ‘abc’

**Result**: attributes ‘Font’ and ‘Heading Font’ are not deleted

**#4**
When a decomposition attributes are stored in repository and then loaded from repository for another decomposition, ‘Font’ and ‘Heading Font’ attributes are not loaded, e.g.: 

Stored attributes:
![image](https://cloud.githubusercontent.com/assets/14101966/16218651/42bd49b0-37c3-11e6-8258-3d0341f9b9d1.png)

Loaded attributes:
![image](https://cloud.githubusercontent.com/assets/14101966/16218662/4c7c293a-37c3-11e6-826a-582b779e1663.png)

**#5**

In an attached specification ‘extendedAttributesReadOnly.yawl’ task ‘abc’ has a variable with ‘Output’ scope and ‘read-only’ setting defined in the decomposition extended attributes. When the specification is saved, no warnings are provided in the Editor. During execution of the specification, a user gets an error message:

![image](https://cloud.githubusercontent.com/assets/14101966/16218675/5fa17c0e-37c3-11e6-9b58-bf0f136d5fd5.png)

**Comment by yawlfoundation** [comment]
1 (a,b): nothing can be done about different browsers rendering fonts and fields differently. The standard layouts work in all browsers.
1 (c): Fixed
1 (d): Fixed

2: Fixed

3,4,5: Duplications (Fixed) of parts of #580
