### ISSUE TITLE
Issues related to default variable-level extended attributes

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#580]
[extendedAttributesVar.yawl.gz](https://github.com/yawlfoundation/yawl/files/326842/extendedAttributesVar.yawl.gz)
[Exception Handler.html.gz](https://github.com/yawlfoundation/yawl/files/326843/Exception.Handler.html.gz)

**#1**

If a variable scope is ‘Output’ and the value of the variable attribute ‘Blackout’ or ‘Read Only’ is set to ‘true’, the Editor does not provide any warnings, a user gets the error screen during execution:
![image](https://cloud.githubusercontent.com/assets/14101966/16251294/24d39f62-3868-11e6-8245-c602be94ee50.png)

**#2**

If a variable scope is ‘Output’ and the value of the variable attribute ‘Hide’ or ‘Hide if’ is set to ‘true’, the Editor does not provide any warnings, a user gets the error screen during execution:
![image](https://cloud.githubusercontent.com/assets/14101966/16251300/305f92d2-3868-11e6-8114-dde044548a6d.png)

**#3**

If the value of ‘Skip Validation’ attribute is set to true for a variable of type ‘int’ and a user enters text value during execution, an exception is thrown (attached, ‘Exception Handler.htm’)

**#4**

Formatting issue when executing the attached specification (‘extendedAttributesVar.yawl’) - ‘Line below’ and ‘Text below’ overlap with the text area (Google Chrome and Firefox):
![image](https://cloud.githubusercontent.com/assets/14101966/16251308/3c449b56-3868-11e6-9a56-01152fcc9b87.png)

**#5**

When a variable attributes are saved in repository and then loaded from repository for a different variable, ‘Font’ attribute is not loaded.

**#6**

When a variable attribute ‘Font’ is deleted, the specification is saved, and ‘Extended Attributes’ for the variable are re-opened, ‘Font’ is still defined.

**Comment by a-pika** [comment]
**#7** 

Attribute 'Fraction Digits' has no effect for variables of type 'double' or 'float'

**Comment by a-pika** [comment]
**#8** 

After the value of attribute 'Max Inclusive' is defined and the specification is saved, the value of 'Max Exclusive' attribute is automatically set equal to the value of 'Max Inclusive' attribute (and vice versa).

**Comment by yawlfoundation** [comment]
1,2: Fixed: those attributes do not make sense for output-only vars, and now do not appear. 

3: Fixed: Note that this turn off validation on the form only, the engine will still not accept an incorrect data type

4: Layout is correct for me in chrome. Note that text areas are resizable in most browsers, and so there is nothing that can be done to prevent a user stretching the text area out over other parts of the form.

<img width="315" alt="chromelayout" src="https://cloud.githubusercontent.com/assets/13515110/17935284/03fda97e-6a1b-11e6-87d3-fc4582469549.png">

5: Fixed

6: Fixed

7: Defn from XML Schema: xs:fractionDigits defines the maximum number of fractional digits (i.e., digits that are after the decimal point) of an xs:decimal datatype (only).

8: Fixed

All in build 701
