### ISSUE TITLE
Exception handling: constraint-related issues

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#581]
[exlet4Constraints.yawl.gz](https://github.com/yawlfoundation/yawl/files/329179/exlet4Constraints.yawl.gz)

**#1**

Net variables are not listed under ‘Data Context’ for Rule Type ‘Pre-case constraint violation’ (if rule type ‘post-case constraint violation’ is selected and then ‘pre-case constraint violation’ is selected again, then net variables are listed under ‘Data Context’):
![image](https://cloud.githubusercontent.com/assets/14101966/16291375/8c812f30-3949-11e6-9148-3608c8997f12.png)

**#2**

Task variables are not listed under ‘Data Context’ for Rule Type ‘Workitem post-constraint violation’ if the variable scope is ‘Output’ (listed if the scope is ‘Input’):
![image](https://cloud.githubusercontent.com/assets/14101966/16291381/a4ea3788-3949-11e6-8ec5-6ee0a62af1f2.png)

(Screenshots are taken using the attached specification ‘exlet4Constraints.yawl’)

**Comment by yawlfoundation** [comment]
both fixed in build 700
