### ISSUE TITLE
Creating MI atomic task instances 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#583]
[MIstart.yawl.gz](https://github.com/yawlfoundation/yawl/files/333902/MIstart.yawl.gz)

Instances of an MI atomic task are created sequentially, i.e., initially only one instance is created, after the first instance is started, other instances are created, e.g., for task ‘MIatomic’ in the attached specification ‘MIstart.yawl’ (all instances of an MI composite task are created at the same time, e.g., for task ‘MIcomposite’).

**Comment by yawlfoundation** [comment]
This is expected behaviour. An MI task is first enabled (as a parent), but the child items are not created until the parent is started.
