### ISSUE TITLE
Resourcing: ‘Choose completers of task’ constraint issue

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#584]
[systemOffer.yawl.gz](https://github.com/yawlfoundation/yawl/files/333929/systemOffer.yawl.gz)

In the attached specification (‘systemOffer.yawl’) tasks ‘a’ and ‘b’ are offered to two different participants; for task ‘b’ constraint ‘Choose completers of task a’ is defined. At run-time task ‘b’ is offered to the completer of task ‘a’ (‘Enable System Offer’ rule for a different participant is ignored).

**Comment by yawlfoundation** [comment]
Expected behaviour: the 'choose completer of task' constraint will offer to the same participant that completed a, not a different one. 'Choose completers' is the familiar task pattern; 'Do not choose completers' is the separation of duties pattern.
