### ISSUE TITLE
Empty distribution set - no warning in the Editor

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#585]
When a user defines ‘System Offer’ rules that result in an empty distribution set (e.g., when using filters or constraints), the Editor does not provide any warnings (enhancement suggestion).

**Comment by yawlfoundation** [comment]
It is impossible to predict at design time whether an empty distribution set will result at runtime. For example, a model may be defined before roles are populated. Distribution sets can only be composed dynamically, at runtime.
