### ISSUE TITLE
Secondary resources issues

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#587]
**#1**

Non-human resource categories can only be selected once in the Editor.

**#2**

When executing a workitem for which secondary resources are defined, a warning is logged, e.g.:
![image](https://cloud.githubusercontent.com/assets/14101966/16441493/46bc4240-3e0e-11e6-994e-8d1611f0f2b9.png)

(No other cases or work items were active)

**Comment by yawlfoundation** [comment]
1. fixed for build 701

2. fixed for next RS build
