### ISSUE TITLE
YAWL examples: Order Fulfilment

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#588]
When executing the ‘order fulfilment’ example (http://www.yawlfoundation.org/yawldocs/orderfulfillment.zip), an error is logged:

![image](https://cloud.githubusercontent.com/assets/14101966/16510295/0c61bad2-3f88-11e6-9e9e-a90ca5fd6cf1.png)

Custom forms seem to be in place:
![image](https://cloud.githubusercontent.com/assets/14101966/16510302/191c42c4-3f88-11e6-8ae2-5490273d7d54.png)

**Comment by yawlfoundation** [comment]
Worked fine for me in testing (see attached). Cannot reproduce.

<img width="524" alt="form" src="https://cloud.githubusercontent.com/assets/13515110/17554624/0eb5389c-5f0c-11e6-8e96-c74132ae3e6b.png">
