### ISSUE TITLE
YAWL examples: yawl4film

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#589]
**#1**
When executing ‘yawl4film’ example (http://www.yawlfoundation.org/yawldocs/yawl4film.zip), an error is logged after a case is started:
![image](https://cloud.githubusercontent.com/assets/14101966/16510409/10b2b2b6-3f89-11e6-81ae-aae31a3fb9b4.png)

**#2**
Custom forms are not found (no ‘yawl4film’ folder in the YAWL installation folder):
![image](https://cloud.githubusercontent.com/assets/14101966/16510414/19e83a40-3f89-11e6-8c85-750366001c18.png)

**#3**
When the specification ‘filmproduction.yawl’ is loaded in the Editor – blank page:
![image](https://cloud.githubusercontent.com/assets/14101966/16510419/25f7a820-3f89-11e6-9982-b7d456ff401b.png)

**Comment by yawlfoundation** [comment]
1: fixed in resource service build 3969
2: awaiting sourcing of custom forms 
3: fixed in editor build 699

**Comment by adamsmj** [comment]
The YAWL4 Film custom forms cannot be sourced, and are no longer relevant in any case. Will close this item
