### ISSUE TITLE
YAWL examples: wListMaker (worklet service example)

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#590]
When executing ‘wListMaker’  example (http://www.yawlfoundation.org/yawldocs/worklet_examples.zip), with the following input:
![image](https://cloud.githubusercontent.com/assets/14101966/16510559/8c9871bc-3f8a-11e6-9e30-d18145dba586.png)

A user gets an error:
![image](https://cloud.githubusercontent.com/assets/14101966/16510566/a6400652-3f8a-11e6-91ff-b9833a25bd5b.png)
![image](https://cloud.githubusercontent.com/assets/14101966/16510571/a9d095a2-3f8a-11e6-99b8-dfa051942b93.png)

**Comment by yawlfoundation** [comment]
fixed in latest worklet service build
