### ISSUE TITLE
Is there a easy way to Merge Two YAWLS? 

### ISSUE THREAD

**Issue by bhanusingh893** [yawlfoundation/yawl#591]
Currently I have two yawls of same name, but version different. right now to merge changes made in version 1 to version 2 i have to actually create manual every task etc. Is there a automated way in which two yawls can be merged easily with the difference?

**Comment by yawlfoundation** [comment]
There's no automated way. The easiest way would be to open both yawl files in a text file differ and merge the differences that way.
