### ISSUE TITLE
Exception handling: action ‘complete workitem’ (errors in the log) 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#592]
[exletMain.yawl.gz](https://github.com/yawlfoundation/yawl/files/483951/exletMain.yawl.gz)
[exletMain.xrs.gz](https://github.com/yawlfoundation/yawl/files/483952/exletMain.xrs.gz)

Exceptions in the log when executing the attached specification (cases are completed as expected):

![image](https://cloud.githubusercontent.com/assets/14101966/18694892/3d6f7f66-7ff1-11e6-9bda-ad3c7f8e30d1.png)
![image](https://cloud.githubusercontent.com/assets/14101966/18694896/43f8ab3c-7ff1-11e6-932f-d2c350912ecf.png)
![image](https://cloud.githubusercontent.com/assets/14101966/18694905/4d01a17a-7ff1-11e6-9ccb-7b75c937fa98.png)

**Comment by a-pika** [comment]
The error in the log seems to be not related to ‘complete workitem’ action and appears for other actions as well:
![image](https://cloud.githubusercontent.com/assets/14101966/18695350/6b555b00-7ff4-11e6-8247-5140c80cf149.png)

**Comment by adamsmj** [comment]
fixed in latest update (also fixed secondary issue in log above re 'problem merging workitem data')
