### ISSUE TITLE
Exception handling: fail workitem issue 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#593]
[exletMain2.yawl.gz](https://github.com/yawlfoundation/yawl/files/483995/exletMain2.yawl.gz)
[exletMain2.xrs.gz](https://github.com/yawlfoundation/yawl/files/483996/exletMain2.xrs.gz)

For the attached specification, after action ‘fail workitem’ is completed, execution does not proceed to the next workitem on the process path.

**Comment by yawlfoundation** [comment]
fixed in latest updates
