### ISSUE TITLE
Exception handling:  ‘continue case/all cases’ issue 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#594]
[exletMain21.xrs.gz](https://github.com/yawlfoundation/yawl/files/484366/exletMain21.xrs.gz)
[exletMain21.yawl.gz](https://github.com/yawlfoundation/yawl/files/484367/exletMain21.yawl.gz)
[exletMain23.xrs.gz](https://github.com/yawlfoundation/yawl/files/484368/exletMain23.xrs.gz)
[exletMain23.yawl.gz](https://github.com/yawlfoundation/yawl/files/484369/exletMain23.yawl.gz)
For the attached specifications, started workitems are listed as ‘suspended’ after actions ‘suspend case/all cases’ -> ‘continue case/all cases’ are executed:
![image](https://cloud.githubusercontent.com/assets/14101966/18701601/db672a1e-8020-11e6-910a-2ba188144a74.png)
![image](https://cloud.githubusercontent.com/assets/14101966/18701606/e0daa0f2-8020-11e6-9444-b17e40754ea1.png)

**Comment by yawlfoundation** [comment]
Working as expected for me. You may have to hit the 'refresh' button (blue arrows at top right of queues) to see changes in status - the queues are updated by pull, not push.

Please check again and let me know.

**Comment by a-pika** [comment]
The workitems are listed as 'suspended' after pressing the 'refresh' button, they are moved to the 'started' queue after pressing the 'Unsuspend' button.

**Comment by yawlfoundation** [comment]
OK, thanks.

Fixed in latest update (resource service build 3987)
