### ISSUE TITLE
Exception handling: removing rules

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#597]
[removingRule.xrs.gz](https://github.com/yawlfoundation/yawl/files/565632/removingRule.xrs.gz)
[removingRule.yawl.gz](https://github.com/yawlfoundation/yawl/files/565631/removingRule.yawl.gz)

**Steps**: upload the attached rules and open the specification in the Editor -> open 'Rule browser' -> select rule type ‘workitem pre-constraint violation’ and remove the rule -> select rule type ‘pre-case constraint violation’ and then select rule type ‘workitem pre-constraint violation’ again.

**Result**: the Rule browser freezes.

**Comment by yawlfoundation** [comment]
fixed in build 719

cause: rule for empty tree left in rule combo
