### ISSUE TITLE
Incorrect number of local net variables displayed 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#599]
[NetVars.yawl.gz](https://github.com/yawlfoundation/yawl/files/568060/NetVars.yawl.gz)
Incorrect number of local net variables displayed in the Editor (for the attached specification):
![image](https://cloud.githubusercontent.com/assets/14101966/19953092/1eb85ed0-a1b6-11e6-9f17-c28882a1e06a.png)

**Comment by yawlfoundation** [comment]
fixed in build 719
