### ISSUE TITLE
Unable to remove a ruleset 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#600]
[FixMajorIssues.xrs.gz](https://github.com/yawlfoundation/yawl/files/568168/FixMajorIssues.xrs.gz)
[FixMajorIssues.yawl.gz](https://github.com/yawlfoundation/yawl/files/568169/FixMajorIssues.yawl.gz)

The attached specification was loaded as a worklet. I opened the Rule browser, removed the first rule (workitem pre-constraint violation) from the ruleset and closed the browser. When I attempt to open the rule browser for the specification again, the Editor ‘freezes’. When I attempt to remove the rule set (attached), I get a notification that the ruleset is removed, however it is still displayed in the ruleset list. Also, there is an error in the log: 
![image](https://cloud.githubusercontent.com/assets/14101966/19954833/ca4a9964-a1c7-11e6-8787-30306e513b60.png)

**Comment by yawlfoundation** [comment]
fixed in build 719

cause: empty tree listed in rule combo
