### ISSUE TITLE
Exception handling: removing a rule 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#603]
[Main6.xrs.gz](https://github.com/yawlfoundation/yawl/files/585117/Main6.xrs.gz)
[Main6.yawl.gz](https://github.com/yawlfoundation/yawl/files/585118/Main6.yawl.gz)

**Steps**: upload the attached ruleset and open the specification -> open the ‘rule browser’ -> remove the first rule -> close the ‘rule browser’ -> open the ‘rule browser’ again

**Result**:
![image](https://cloud.githubusercontent.com/assets/14101966/20206245/b4fe2724-a82a-11e6-83b5-a8e6621603cf.png)

**Comment by yawlfoundation** [comment]
This problem is resolved in the latest builds
