### ISSUE TITLE
YAWL 4.1 Editor unable to add output data binding using a Data Gateway

### ISSUE THREAD

**Issue by fmannhardt** [yawlfoundation/yawl#605]
The specification generated by the YAWL 4.1 editor (build 734) when using a Data Gateway as output binding is not accepted by the YAWL engine.

The following output binding declaration:
![grafik](https://cloud.githubusercontent.com/assets/3202998/26752897/7cd663fe-485a-11e7-8c24-650db30e53b5.png)

Here the error message:
![grafik](https://cloud.githubusercontent.com/assets/3202998/26752913/d08c1c78-485a-11e7-859a-08973eaff5bd.png)

Here the specification:
[test.zip](https://github.com/yawlfoundation/yawl/files/1049556/test.zip)

**Comment by yawlfoundation** [comment]
fixed in latest editor update (build 735)

**Comment by fmannhardt** [comment]
Thanks, it works except for a small detail. The output binding is not displayed in the dialog:
![grafik](https://user-images.githubusercontent.com/3202998/27507468-46d0e0e6-58d0-11e7-9253-83a08f0c69dd.png)
However, it can be uploaded to the YAWL Engine and works as expected.

**Comment by fmannhardt** [comment]
Also, it seems not to save the 'query' when updating it. I first added the query '#external:SimpleExternalDBGatewayImpl:test' and now it is stuck at this value. 

I want to change it to '#external:SimpleExternalDBGatewayImpl:Main' and the UI displays '#external:SimpleExternalDBGatewayImpl:Main'. In the XML specification it shows:

>           <completedMappings>
>             <mapping>
>               <expression query="#external:SimpleExternalDBGatewayImpl:test" />
>               <mapsTo>test</mapsTo>
>             </mapping>
>             <mapping>
>               <expression query="#external:SimpleExternalDBGatewayImpl:Main" />
>               <mapsTo>Main</mapsTo>
>             </mapping>
>           </completedMappings>

There seems to be an issue with removing the existing mapping, thus, two of them are now present in the XML.

**Comment by ahense** [comment]
[test.yawl.zip](https://github.com/yawlfoundation/yawl/files/1153123/test.yawl.zip)
![sc](https://user-images.githubusercontent.com/9006633/28275742-1d8e7ee4-6b15-11e7-8944-ae36ab21a7e6.png)

I still get the same error using editor build 735.

**Comment by adamsmj** [comment]
Finally fixed in latest update (762)
