### ISSUE TITLE
YTask.getInformation and YWorkItem.toXML return invalid XML because taskName or taskDocumentation contain unescaped characters

### ISSUE THREAD

**Issue by mlawry** [yawlfoundation/yawl#614]
`YTask` class in package `org.yawlfoundation.yawl.elements`, `getInformation()` method.

If task name or documentation contain characters such as '&', then the resulting XML returned doesn't escape the '&', resulting invalid XML.

    result.append("<taskName>");
    result.append(_name != null ? _name :
            _decompositionPrototype != null ? _decompositionPrototype.getID() : "null");
    result.append("</taskName>");
    
    if (_documentation != null) {
        result.append("<taskDocumentation>");
        result.append(_documentation);
        result.append("</taskDocumentation>");
    }

**Comment by mlawry** [comment]
`YWorkItem` class in package `org.yawlfoundation.yawl.engine`, `toXml()` method.

Same problem, may be should use `StringUtil.wrapEscape` instead of plain `StringUtil.wrap`.

    xml.append(StringUtil.wrap(_task.getName(), "taskname"));
    xml.append(StringUtil.wrap(getDocumentation(), "documentation"));

**Comment by yawlfoundation** [comment]
fixed - thanks for locating these issues
