### ISSUE TITLE
WorkQueueGatewayClient not thread-safe

### ISSUE THREAD

**Issue by fmannhardt** [yawlfoundation/yawl#617]
The [WorkQueueGatewayClient](https://github.com/yawlfoundation/yawl/blob/master/src/org/yawlfoundation/yawl/resourcing/rsInterface/WorkQueueGatewayClient.java) is not thread-safe. Many methods use a shared 'params' field for not apparent reason. This may lead to information from other requests leaking through, which is both a security concern & not correct.

The easiest solution would be to remove the 'params' field and create a new map for every request as already done in a lot of methods, which use 'prepareParamMap'.

**Comment by adamsmj** [comment]
class is now thread safe
