### ISSUE TITLE
WorkItemRecord.toXML() returns invalid XML when taskName or documentation contains &

### ISSUE THREAD

**Issue by mlawry** [yawlfoundation/yawl#618]
This is similar to issue #614.

WorkItemRecord.java's toXML() method calls:

    xml.append(StringUtil.wrap(_taskName, "taskname"));
    xml.append(StringUtil.wrap(_documentation, "documentation"));

When `_documentation` contains '&' the output is invalid because it is not escaped as `&amp;`.
Same goes for `_taskName`.

May be should use `StringUtil.wrapEscaped` instead of `StringUtil.wrap`.

**Comment by mlawry** [comment]
May be all `wrap` calls in `WorkItemRecord.toXML()` method should use `StringUtil.wrapEscaped`?

**Comment by adamsmj** [comment]
Fixed and in repo.

Most data is already escaped elsewhere, only necessary to do data members as required
