### ISSUE TITLE
Seeing double menu strips after update

### ISSUE THREAD

**Issue by Bazmundi** [yawlfoundation/yawl#620]
Updates from 4.1 to 4.2.

When Yawl editor came back up, many of the menu strips were replicated.
![double bar](https://user-images.githubusercontent.com/1772587/41814389-ae4e2408-7789-11e8-8837-f1b43305c27d.png)

**Comment by adamsmj** [comment]
The update did not completely finish. Please go to your YAWL installation directory, then /editor/plugins sub-dir, and inside that delete all files that end in '4.1.jar', then restart the editor.
