### ISSUE TITLE
Case creation causes 404 error for non-administrators

### ISSUE THREAD

**Issue by tomash87** [yawlfoundation/yawl#621]
When a non-administrator user with "Manage cases" privilege tries to launch new case, a 404 error is displayed with message "There appears to be a problem. Please return to the previous page." and case is not created.

Detailed steps:
1. Set up a brand new installation of YAWL
2. Load the attached specification and org data: [L01.zip](https://github.com/yawlfoundation/yawl/files/2353974/L01.zip).
3. Create a new user with First name: Bill, Last name: Manager, User ID: bm, Password: YAWL
4. Add privilege "Manage cases" to that user
5. Log in into that user
6. Enter "Cases"
7. Select a specification and click "Launch case"
8. The abovementioned error occurs.

The specification and org data were created to reproduce the example of credit application from Sections 3.3-3.4 of the user manual v4.2. The error occurs only for non-admin users, administrators can launch new cases without errors.

Version information: YAWL version 4.2 | Engine build 4.2.1519 (2018/08/03 14:11) | Resource Service build 4.2.4030 (2018/08/14 11:31)
Verified on MacOS and Windows.

**Comment by adamsmj** [comment]
Fixed in the latest update (resource service). The authorisations filter for the case mgt page was being overly choosy.
