### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by Marco-Sulla** [yawlfoundation/yawl#623]
I quote the [documentation](http://www.yawlfoundation.org/manuals/YAWLUserManual4.2.pdf):

> Decompositions can have a number of variables(or parameters) defined for them, describing 
> what data must be supplied to a running net or task instance,and what data that net or task 
> instance will eventually deliver. Each variable has a name it may be referenced by, a type dictating 
> valid values it may store, a designation (or usage) indicating how that data may be used,and 
> a scope defining the visibility of the parameter. Variables can belong to one of two scopes, which 
> we’ll refer to as net scope and task scope. At runtime, every net, and every task instance with a 
> decomposition, will have data stored as a number of variables belonging to it.   To get data from 
> a net instance to a task instance within the net,  or visa-versa,  we require a data transfer. In 
> YAWL, all data is passed this way – from net-level to task-level when a task instance starts, 
> and from task-level back to net-level when the task instance completes; data cannot be directly 
> transferred from one task instance to another. Valid designations for a task variable 
> are Input,Output or both Input & Output.  A task variable with an input designation is one where 
> we expect data to be delivered from a net-level variable to that variable at run-time.  A task 
> variable with an output designation it expected to have its data output to a containing net-level 
> variables once a task instance has completed.

I see in the YAWL Editor interface that what the documentation defines as "designation" is called "scope" in the interface.

**Comment by adamsmj** [comment]
While the distinction between designation (usage) and scope is defined in the more formal description of the data perspective in Chapter 3 of the manual, for the editor UI it was decided that the heading 'Scope' be used in data dialogs for improved usability and easier understanding.
