### ISSUE TITLE
There is no support for codelets that extends from a derived class of AbstractCodelet

### ISSUE THREAD

**Issue by Marco-Sulla** [yawlfoundation/yawl#625]
I tried to create a simple custom `MyAbstractCodelet extends AbstractCodelet`, and I tried to apply `MyAbstractCodelet` to a test codelet. YAWL does not see it. It seems that only the codelets that extends from `AbstractCodelet` only are exposed. A simple `instanceof` will do the trick.

**Comment by adamsmj** [comment]
fixed in latest update. Actually affected all plugin grandchild classes
