### ISSUE TITLE
YDataValidator does not expose SchemaHandler handler

### ISSUE THREAD

**Issue by Marco-Sulla** [yawlfoundation/yawl#626]
The class `YDataValidator` uses internally a `SchemaHandler`, and does not expose it publicly. `SchemaHandler` is full of useful methods. One of them is `getTypeMap()`, that returns all the schemas of the parameter types as a map of `org.jdom2.Element`s.

Please, can you add a simple `getHandler()` to `YDataValidator`? I have to use reflections for now.

PS: I get the `YDataValidator` with 

```java
parameter.getParentDecomposition().getSpecification().getDataValidator();
```

where `parameter` is one of the `YParameter`. Can't you simply pass the `YDecomposition` to the `AbstractCodelet` constructor?

**Comment by adamsmj** [comment]
added YDataValidator#getSchemaHandler
