### ISSUE TITLE
Implement a YParameter.getValue(Element inData)

### ISSUE THREAD

**Issue by Marco-Sulla** [yawlfoundation/yawl#627]
I think it will be really more simple if `YParameter` will have a method `getValue(Element inData)`. Now you have to get the `YParameter` name and invoke `AbstractCodelet.getParameterValue(String paramName)`. This is a bit strange for me. 

Furthermore `AbstractCodelet.getParameterValue()` is protected and can't be used in utility classes, for example. I had to create an utility that extends from a `FakeAbstractCodelet`, which `execute()` method throws a `NotImplementedException`.

**Comment by adamsmj** [comment]
A YParameter is a template for a data variable. Due to a separation of concerns, it would be inappropriate for a YParameter to deal with runtime data values. Codelets only exist at runtime, so that's the appropriate place for any methods that handle runtime data. Closed without change.
