### ISSUE TITLE
"Phantom" decomposition return values

### ISSUE THREAD

**Issue by mmcfarland-cavulus** [yawlfoundation/yawl#629]
When creating a decomposition, there appear to be two places where values are enumerate: within `<task></task>` and also within `<decomposition></decomposition>`. The latter values are displayed in the workitem Decomposition Variables pane.

We've hit a situation where a completedMapping defined in the former (let's say it maps to the Net-level variable `randomNetLevelVar`), but not defined as an outputParam in the latter, will not show up in the YAWL editor, but it _will_ attempt to assign a value to that Net-level variable. In this case, given that there's no actual return value, the Net-level variable is emptied of data. Therefore, any downstream workitems that depend on that same variable will, mysteriously, have no data to work with.

[test_spec.zip](https://github.com/yawlfoundation/yawl/files/3618020/test_spec.zip)

**Comment by adamsmj** [comment]
fixed in previous update
