### ISSUE TITLE
Istallation not working on MacOs Catalina

### ISSUE THREAD

**Issue by ozzop** [yawlfoundation/yawl#630]
Hi, I tried to install YAWL on my Macbook with MacOs Catalina but the YAWL-4.2-osx-installer.app file crashes after I open it. I tried to open it with the terminal via
`sudo open YAWL-4.2-osx-installer.app`
but I get
`LSOpenURLsWithRole() failed with error -10810 for the file /Users/myuser/Downloads/output/YAWL-4.2-osx-installer.app`.

I've read the YAWL user installation guide and I've set up the two environment variables `JAVA_HOME` and `CATALINA_HOME` and also edited the two files in my Tomcat folder. My `java -version` output is
```
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```
and I'm using Tomcat 9.0.30 right now. Hope this can be fixed.

**Comment by adamsmj** [comment]
The version of the installer packages we have used in the past no longer work with the newer versions of OSX. We are working on upgrading the installers and should have working versions soon.

In the meantime, you can download the YAWL core war files from: [https://github.com/yawlfoundation/yawl/releases/download/v4.2/YAWL_CoreServices_4.2.zip] , then unzip them in your tomcat webapps directory and start tomcat. That will give you a working version. You will also need to download the editor from here: [https://github.com/yawlfoundation/yawl/releases/download/v4.2/YAWLEditor4.2.zip]

**Comment by yawlfoundation** [comment]
The new packages have now been released and tested to work successfully, so am closing this one.
