### ISSUE TITLE
Mac OS Freeze at Calendar view

### ISSUE THREAD

**Issue by Maetes** [yawlfoundation/yawl#634]
When i log into the logon page and click on the Calendar button all is fine. When i want to switch to another view for instance Cases or so on, it don't let me go so i have to rerun the engine... Other views are fine. It's just the Calendar view...

I'm using Java 14.0.1 with Mac OS Catalina 10.15.6

**Comment by adamsmj** [comment]
This was a validation bug - fixed in the latest update
