### ISSUE TITLE
Enable logging in Engine / Standalone.jar

### ISSUE THREAD

**Issue by Makeda21code** [yawlfoundation/yawl#636]
Hi, created a new log4j Logger instance in org\yawlfoundation\yawl\logging\SpecHistory.java but I get no output in Console and Logfiles. I set log4j.rootLogger=TRACE, syslog in log4j.properties. I also tried System.out.println(). It seems like all log messages are suppressed. How can I enable them again?

**Comment by yawlfoundation** [comment]
Which version are you using? In later versions, the log4j configs are read from log4j2.xml

**Comment by Makeda21code** [comment]
yes, you are right.  I thought engine logging runs in standalone.
