### ISSUE TITLE
Data variable freezes when clicked on

### ISSUE THREAD

**Issue by lawrencematthew19942016** [yawlfoundation/yawl#638]
Does anyone know why this happens? 
![frozen](https://user-images.githubusercontent.com/80303704/112138874-2443c880-8c26-11eb-9996-ad5fd4f0856e.jpg)

**Comment by adamsmj** [comment]
I can't replicate. Can you please give some details of your OS, Java version, etc?

**Comment by Hira92** [comment]
I am facing same issue. By clicking on Data Variables elipses, nothing happens.
Windows 10
JDK JRE 16

**Comment by Robin0815** [comment]
I faced the same problem on multiple systems.
But updating the YAWL Editor to build 772 from version 769 fixed the problem for me on all systems. The Java and Windows versions had no effect. I tried it on Windows 10 version 1809 with Java 8 (1.8.0_292) and Windows 10 20H2 with Java 11 (11.0.11+9).

**Comment by adamsmj** [comment]
That makes sense: there was a library addition between 769 -772 to accomodate later versions of Java introducing some Swing issues. 

So the fix for this problem is to update to the latest version of the editor. Marking as closed.
