### ISSUE TITLE
MacOSx Installer misbehaving on YAWL Editor Version

### ISSUE THREAD

**Issue by MariFio** [yawlfoundation/yawl#639]
Hi all,
first of all I wanna thank you the YAWL community for the tool and all the capabilities which are offered.
I am opening this issue because, since the latest software release (4.5.1), on MacOSx, I am experiencing an issue with the editor.
In particular, it happens that the YAWL editor which is installed is the one related to v4.3.1.
This causes conflicts and functionalities to not work.

I am running MacOS BigSur on a MacBook Pro (Retina, 15-inch, Mid 2014) - if this could be of support.

Any hint?
Thanks in advance.

**Comment by yawlfoundation** [comment]
Hi MariFio, 
Thanks for your warm words.
There was one old file left in the last release that was the cause of your issue. Please try downloading the YAWL installer again and you'll find the issue has been resolved.
